export const SESSION_ID_STORAGE_KEY = 'search-id';
export const DATE_FORMAT            = 'DD/MM/yyyy HH:mm';

//actions
export const FINISHED_ADD_SEARCH_RESULT_ACTION = 'FINISHED_ADD_SEARCH_RESULTACTION';
export const STARTED_ADD_SEARCH_RESULT_ACTION = 'STARTED_ADD_SEARCH_RESULT_ACTION';
export const FAILED_ADD_SEARCH_RESULT_ACTION  = 'FAILED_ADD_SEARCH_RESULT_ACTION';

export const FINISHED_FETCHING_SEARCHES_ACTION = 'FINISHED_FETCHING_SEARCHES_ACTION';